language: python
python:
      - "3.4"
      - "3.5"
      - "3.6"
sudo: false

before_install: pip install codecov
after_success:  codecov

install:
    - pip install -r requirements.txt

script: nosetests -a '!numpress'  test/ --with-coverage
